sudo: false
os:
  - windows
dist: bionic
language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: beta
    - rust: nightly
  fast_finish: true
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then rustup default $TRAVIS_RUST_VERSION-x86_64-pc-windows-msvc ; fi
install:
  - rustup component add clippy rustfmt
script:
  - cargo clippy --tests
  - cargo test
  - cargo doc --no-deps
  - cargo fmt --all -- --check
