sudo: false
os:
  - windows
dist: bionic
language: rust
rust:
  - stable-x86_64-pc-windows-msvc
  - beta-x86_64-pc-windows-msvc
  - nightly-x86_64-pc-windows-msvc
matrix:
  allow_failures:
    - rust: beta-x86_64-pc-windows-msvc
    - rust: nightly-x86_64-pc-windows-msvc
  fast_finish: true
install:
  - rustup component add clippy rustfmt
script:
  - cargo clippy --tests
  - cargo test
  - cargo doc --no-deps
  - cargo fmt --all -- --check
